export type BackTopProps = {
	mode ?: 'round' | 'half-round',
	parentId ?: string,
	scrollTop ?: number,
	offset ?: number,
	right ?: string | number,
	bottom ?: string | number,
	duration ?: number,
	icon ?: string,
	iconSize ?: string | number,
	text ?: string,
	textSize ?: string | number,
	textColor ?: string,
	width ?: string | number,
	height ?: string | number,
	radius ?: string | number,
	bgColor ?: string,
	zoom ?: boolean,
	zIndex ?: number,
	customStyle ?: UTSJSONObject,
}