import { CollapseActiveName } from "../rice-collapse"

export type CollapseItemProps = {
	name ?: CollapseActiveName,
	icon ?: string,
	title ?: string | number,
	value ?: string | number,
	contentText ?: string | number,
	duration ?: number,
	border ?: boolean,
	contentBorder ?: boolean,
	arrow ?: boolean,
	clickable ?: boolean,
	disabled ?: boolean,
	readonly ?: boolean,
	titleStyle ?: UTSJSONObject,
	valueStyle ?: UTSJSONObject,
	contentStyle ?: UTSJSONObject,
	customStyle ?: UTSJSONObject
}