export type TagType = 'primary' | 'success' | 'warning' | 'error' | 'default'

export type TagProps = {
	type ?: TagType,
	size ?: 'large' | 'small',
	color ?: string,
	text ?: string | number,
	icon ?: string,
	textColor ?: string,
	textSize ?: string | number,
	show ?: boolean,
	plain ?: boolean,
	plainFill ?: boolean,
	round ?: boolean,
	mark ?: boolean,
	closeable ?: boolean,
	customStyle ?: UTSJSONObject,
}